name: Build and Publish ESPHome firmware and website

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.yaml'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish-est-poe-32-bluetooth-proxy:
    name: Publish EST-PoE-32 Bluetooth Proxy
    uses: EverythingSmartHome/firmware/.github/workflows/esphome-build.yml@main
    with:
      files: EST-PoE-32/ESPHome/est-poe-32-bluetooth-proxy.yaml
      name: EST-PoE-32 Bluetooth Proxy
      manifest_filename: est-poe-32-bluetooth-proxy-manifest.json
      clean: false
      esphome_version: latest
      directory_name: est-poe-32-bluetooth-proxy
  publish-est-poe-32-all-gpios:
    name: Publish EST-PoE-32 all GPIOs
    uses: EverythingSmartHome/firmware/.github/workflows/esphome-build.yml@main
    with:
      files: EST-PoE-32/ESPHome/est-poe-32-all-gpios.yaml
      name: EST-PoE-32 all GPIOs
      manifest_filename: est-poe-32-all-gpios-manifest.json
      clean: false
      esphome_version: latest
      directory_name: est-poe-32-all-gpios
  publish-est-esp32-devkit-bluetooth-proxy:
    name: Publish EST-ESP32-DevKit Bluetooth Proxy
    uses: EverythingSmartHome/firmware/.github/workflows/esphome-build.yml@main
    with:
      files: EST-ESP32-DevKit/ESPHome/est-esp32-devkit-bluetooth-proxy.yaml
      name: EST-ESP32-DevKit Bluetooth Proxy
      manifest_filename: est-esp32-devkit-bluetooth-proxy-manifest.json
      clean: false
      esphome_version: latest
      directory_name: est-esp32-devkit-bluetooth-proxy
  publish-est-esp32-devkit-all-gpios:
    name: Publish EST-ESP32-DevKit all GPIOs
    uses: EverythingSmartHome/firmware/.github/workflows/esphome-build.yml@main
    with:
      files: EST-ESP32-DevKit/ESPHome/est-esp32-devkit-all-gpios.yaml
      name: EST-ESP32-DevKit all GPIOs
      manifest_filename: est-esp32-devkit-gpios-manifest.json
      clean: false
      esphome_version: latest
      directory_name: est-esp32-devkit-gpios
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [publish-est-poe-32-bluetooth-proxy, publish-est-poe-32-all-gpios, publish-est-esp32-devkit-bluetooth-proxy, publish-est-esp32-devkit-all-gpios]
    steps:
      - name: Checkout gh-pages Branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: 'gh-pages'

      - name: Copy Files from gh-pages Branch
        run: |
          mkdir _site/
          cp -r gh-pages/* _site/
          cp -r static _site/
          
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v2

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
